version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: microservices_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_MULTIPLE_DATABASES: auth_db,tasks_db
    ports:
      - "5433:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
      - ./init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: microservices_rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - app_network

  auth_service:
    build:
      context: ./auth_service
      dockerfile: Dockerfile
    container_name: auth_service
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/auth_db
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - JWT_SECRET=super_secret_key_12345
    volumes:
      - ./logs/auth:/app/logs
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - app_network

  task_service:
    build:
      context: ./task_service
      dockerfile: Dockerfile
    container_name: task_service
    restart: always
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/tasks_db
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
      - JWT_SECRET=super_secret_key_12345
    volumes:
      - ./logs/tasks:/app/logs
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - app_network

  task_worker:
    build:
      context: ./task_service
      dockerfile: Dockerfile
    container_name: task_worker
    restart: always
    command: python worker.py
    environment:
      - DATABASE_URL=postgresql://user:password@postgres:5432/tasks_db
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672/
    volumes:
      - ./logs/tasks:/app/logs
    depends_on:
      - postgres
      - rabbitmq
    networks:
      - app_network

volumes:
  pg_data:

networks:
  app_network:
    driver: bridge
